name: Release to PyPI

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # chỉ cần nếu dùng Trusted Publishing (OIDC)
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build sdist and wheel
        run: python -m build --sdist --wheel --outdir dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          # Nếu KHÔNG dùng OIDC, bỏ permissions.id-token ở trên
          # và thêm dòng dưới:
          # password: ${{ secrets.PYPI_API_TOKEN }}
